WITH BASE AS
(
    SELECT UPPER(SPLIT_PART(EXTERNAL_USER_ID, '_', 1)) AS COUNTRY,
           EXTERNAL_USER_ID,
           CASE WHEN IN_CONTROL_GROUP='true' THEN True ELSE False END AS CONTROL_GROUP,
           MIN(CAST(TIME AS timestamp)::DATE) AS ENTRY_DATE
    FROM CO_WRITABLE.GLOBAL_BRAZE_AIRFLOW
    WHERE  CAMPAIGN_NAME = 'BR_LOCAL_ONEOFF_PUSH_EMERGENCY_HDH_BELO HORIZONTE_TESTE_IMPACTO_01022024'
      AND COUNTRY = 'BR'
    GROUP BY 1,2,3 
),
ORDERS AS
(
    SELECT B.COUNTRY, B.EXTERNAL_USER_ID, B.CONTROL_GROUP, B.ENTRY_DATE,
           COUNT(DISTINCT O.ORDER_ID) AS ORDERS,
           COUNT(DISTINCT IFF(O.VERTICAL='Turbo',O.ORDER_ID,NULL)) AS TURBO_ORDERS
    FROM BASE B
    LEFT JOIN (
                SELECT * FROM OPS_GLOBAL.GLOBAL_ORDERS WHERE COUNT_TO_GMV
                ) O
    ON B.EXTERNAL_USER_ID = CONCAT(UPPER(O.COUNTRY),'_',O.STOREKEEPER_ID)
       AND O.CREATED_AT::DATE >= B.ENTRY_DATE
       AND O.CREATED_AT::DATE < B.ENTRY_DATE+10
    GROUP BY 1,2,3,4
),
TOTALS AS 
(
    SELECT COUNTRY, CONTROL_GROUP,
           COUNT(EXTERNAL_USER_ID) AS BASE,
           COUNT(IFF(ORDERS>0,EXTERNAL_USER_ID,NULL)) AS ACTIVE_USERS,
           SUM(ORDERS) AS ORDERS,
           SUM(TURBO_ORDERS) AS TURBO_ORDERS
    FROM ORDERS
    GROUP BY 1,2
) SELECT * FROM TOTALS;